### ISSUE TITLE
dumb question: how to use the model parameters

### ISSUE THREAD

**Issue by jonathanstrong** [SuperFluffy/rust-recursive-least-squares#3]
this might be a dumb question, but would it be possible to explain how to utilize the model's parameters in the documentation? what I mean is, what operations are needed to perform filtering / predicting on an input row? I'm getting useful results from doing `model.weight_ref().dot(&xs)` where `xs` is a `ArrayBase<S, Ix1>`, but am not sure how gain comes into it. also - on the data I tested it on, something like `1e-3` for `initialization_factor` and `1.0` for `forgetting_factor` is working best. what are very broad guidelines for what to set those variables to?

thank you!

**Comment by SuperFluffy** [comment]
Heya! I think your best chance is to jump to Haykin's Adaptive Filter Theory (see the link in the README) and go from there. If I recall, I have pretty much used their terminology. I have written this library to implement the FORCE algorithm for learning in a chaotic neural network, but I haven't really pursued it since then, so I don't have a good feeling for recursive least squares to give you suggestions.
